### ISSUE TITLE
SPAM Threshold always false

### ISSUE THREAD

**Issue by agillis** [POSSA/Caller-ID-Superfecta#242]
SPAM Threshold never returns true. This is because the variable has the wrong case.

source-PhoneSpamFilter.module line line 32 should be

if ($score > $run_param['SPAM_threshold']) {

not

if ($score > $run_param['SPAM_Threshold']) {

t in threshold is lower case.

**Comment by lgaetz** [comment]
I searched thru all the version branches at this repo and can't find where this is the case. What version of Superfecta are you using?

**Comment by agillis** [comment]
I'm using the latest version (2.11.16). I can see it in your source tree
here

https://github.com/POSSA/Caller-ID-Superfecta/blob/release/2.11/sources/source-PhoneSpamFilter.module

Line 31 needs a small t in threshold

Should be

if ($score > $run_param['SPAM_threshold']) {

On Tue, Mar 10, 2015 at 3:26 PM, Lorne Gaetz <notifications@github.com>
wrote:

> I searched thru all the version branches at this repo and can't find where
> this is the case. What version of Superfecta are you using?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/POSSA/Caller-ID-Superfecta/issues/242#issuecomment-78128790>
> .
>



-- 
Andrew Gillis
Lead Developer VortexBox
vortexbox.org

**Comment by lgaetz** [comment]
Looks good to me, and my testing is confirming it works as expected. The variable `$run_param['SPAM_Threshold']` needs to match the `$source_param['SPAM_Threshold']` as defined on line 8. Furthermore, if the variable was spelled incorrectly on line 31 as you say, any non-zero spam $score would ALWAYS exceed the spam threshold and all calls would be flagged as SPAM.

There are some bugs around SPAM scoring and reporting noted in tickets #161, #162, and #163 but all have been addressed in Superfecta ver 12. Is it possible you are seeing is related to one of those tickets?

**Comment by agillis** [comment]
Your right those fixes do look like they would resolve my problem. I
installed 12.0.1 on my box but it doesn't look like it works with FreePBX
12.0.43. The GUI interface is all messed up and none of the buttons work.

On Wed, Mar 11, 2015 at 10:43 AM, Lorne Gaetz <notifications@github.com>
wrote:

> Looks good to me, and my testing is confirming it works as expected. The
> variable $run_param['SPAM_Threshold'] needs to match the
> $source_param['SPAM_Threshold'] as defined on line 8. Furthermore, if the
> variable was spelled incorrectly on line 31 as you say, any non-zero spam
> $score would ALWAYS exceed the spam threshold and all calls would be
> flagged as SPAM.
>
> There are some bugs around SPAM scoring and reporting noted in tickets
> #161 <https://github.com/POSSA/Caller-ID-Superfecta/issues/161>, #162
> <https://github.com/POSSA/Caller-ID-Superfecta/issues/162>, and #163
> <https://github.com/POSSA/Caller-ID-Superfecta/issues/163> but all have
> been addressed in Superfecta ver 12. Is it possible you are seeing is
> related to one of those tickets?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/POSSA/Caller-ID-Superfecta/issues/242#issuecomment-78276380>
> .
>



-- 
Andrew Gillis
Lead Developer VortexBox
vortexbox.org

**Comment by tm1000** [comment]
Hey Andrew. Nice to see you around again.

It is indeed coded to work with FreePBX 12. Please attach a screen shot of your issue if you can

**Comment by agillis** [comment]
OK I figured it out. When I installed 12.0.1 the installer did not create
the symbolic link to /var/www/html/admin/modules/superfecta/assets/ so the
javascript files could not be found. I added the symbolic link manually and
now the new configuration web GUI is working.

It is still not marking SPAM calls though. I'm using PhoneSpamFilter and as
you can see from the debug message it's not marking the call even though I
have the threshold set to 1.

Executing PhoneSpamFilter
Searching PhoneSpamFilter ...
value of 3 returned ...
Not a SPAM caller
result  took 0.1870 seconds.

On Wed, Mar 11, 2015 at 1:21 PM, Andrew Nagy <notifications@github.com>
wrote:

> Hey Andrew. Nice to see you around again.
>
> It is indeed coded to work with FreePBX 12. Please attach a screen shot of
> your issue if you can
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/POSSA/Caller-ID-Superfecta/issues/242#issuecomment-78310929>
> .
>



-- 
Andrew Gillis
Lead Developer VortexBox
vortexbox.org

**Comment by tm1000** [comment]
"the installer did not create"

The installer does not. "Apply Changes" does.

**Comment by tm1000** [comment]
Also im pretty sure you'd have to re-save the values from PhoneSpamFilter so that the variable is in the right casing.

**Comment by agillis** [comment]
I'm really trying to find out what the problem is and I'm getting closer. I added some more debugging to the code. You may want to make this a permanent addition to the code. It tells what SPAM_Threshold is actually set to (or what the code thinks its set to)

$this->DebugPrint(' SPAM_Threshold set to ' . $run_param['SPAM_Threshold'] . ' ... ');

I set SPAM_Threshold to 1 in the GUI and for some reason it comes back as 10. This is why it's not working. Whatever I set SPAM_Threshold to it always shows up as 10.

 Executing PhoneSpamFilter
Searching PhoneSpamFilter ... 
value of 3 returned ... 
SPAM_Threshold set to 10 ... 
Not a SPAM caller
result  took 0.1747 seconds.

**Comment by tm1000** [comment]
Your values are not being saved correctly. Are you sure there are no javascript errors on your system? This applies both to 2.11 and 12 which use javascript (ajax) to save values.

**Comment by agillis** [comment]
I installed and applied changes. I was getting javascript error until I added the symbolic link manually.

I have tried a lot of different values for the SPAM Threshold and it always shows up as 10.

**Comment by agillis** [comment]
I have the javascript debug console open in Chrome while I am access the page. I don't see any more errors now that I have the links.

**Comment by agillis** [comment]
I just did a dump of my SQL database. Looks like the SPAM_Threshold is set to 5. This is interesting since it's set to 1 in the GUI and it is returning 10 when it get's to the script.

So the base_Default SPAM_threshold is what is being set by the web GUI.

I can't tell what the script uses but it's not this value.

Again I still think there is a problem with the name SPAM_threshold not SPAM_Threshold



LOCK TABLES `superfectaconfig` WRITE;
INSERT INTO `superfectaconfig` VALUES ('base_Default','order','1');
INSERT INTO `superfectaconfig` VALUES ('base_Default','Curl_Timeout','3');
INSERT INTO `superfectaconfig` VALUES ('base_Default','SPAM_Text','(SPAM)');
INSERT INTO `superfectaconfig` VALUES ('base_Default','sources','Asterisk_Phonebook,Superfecta_Cache,PhoneSpamFilter,Telco_Data,Trunk_Provided');
INSERT INTO `superfectaconfig` VALUES ('Trunk_Provided','Ignore_Keywords','unknown, wireless, toll free, unlisted');
INSERT INTO `superfectaconfig` VALUES ('Superfecta_Cache','Cache_Timeout','120');
INSERT INTO `superfectaconfig` VALUES ('PhoneSpamFilter','SPAM_Threshold','5');
INSERT INTO `superfectaconfig` VALUES ('new','sources','PhoneSpamFilter');
INSERT INTO `superfectaconfig` VALUES ('base_Default','DID','');
INSERT INTO `superfectaconfig` VALUES ('base_Default','SPAM_Text_Substitute','N');
INSERT INTO `superfectaconfig` VALUES ('base_Default','multifecta_timeout','1.5');
INSERT INTO `superfectaconfig` VALUES ('base_Default','processor','superfecta_single.php');
INSERT INTO `superfectaconfig` VALUES ('base_Default','Prefix_URL','');
INSERT INTO `superfectaconfig` VALUES ('base_Default','spam_destination','app-blackhole,zapateller,1');
INSERT INTO `superfectaconfig` VALUES ('base_Default','spam_interceptor','Y');
INSERT INTO `superfectaconfig` VALUES ('base_Default','CID_rules','');
INSERT INTO `superfectaconfig` VALUES ('base_Default','SPAM_threshold','1');
INSERT INTO `superfectaconfig` VALUES ('Default_PhoneSpamFilter','SPAM_Threshold','10');
INSERT INTO `superfectaconfig` VALUES ('Default_Trunk_Provided','Ignore_Keywords','unknown, toll free, unlisted, (N/A)');

**Comment by tm1000** [comment]
If you "applied changes" and you still had to symlink manually there are bigger issues at work here. If Lorne can't replicate it then there are bigger issues at work here. I will check in about two hours and see if this is working and if it's working for me then I really don't know what to tell you other than there is a system wide problem with your system relating to the first fact of apply changes not symlinking (permissions?)

"10" is the default and comes into play if there is no value returned from the database. If you are seeing "1" in the GUI but "5" in the database I can not even see how that is remotely possible.

**Comment by agillis** [comment]
It still a bit confusing how all this works. I just figured out how to set the Default_PhoneSpamFilter SPAM_Threshold. I guess I didn't realize there were two different thresholds one for the plug-in and one for the system. Now that I have BOTH thresholds set to 1 it's working as expected.

You might want to add this line to your code.
$this->DebugPrint(' Plug-in SPAM Threshold set to ' . $run_param['SPAM_Threshold'] . ' ... ');

That way somebody looking at the debug will realize there is something wrong with their plug-in settings not their system settings.

Thanks a lot for helping me figure this out!!


This is a new install of the FreePBX iso from last week. So if my DB is corrupt I would say other users will have this problem. Try installing FreePBX iso and then upgrading the Superfecta plug-in to the latest. That is all I did.
